### ISSUE TITLE
Use c

### ISSUE THREAD

**Issue by Superbro525Alt** [spacey-sooty/small-os#1]
Have a look at this:
[https://wiki.osdev.org/Creating_an_Operating_System](https://wiki.osdev.org/Creating_an_Operating_System)

**Comment by spacey-sooty** [comment]
> Have a look at this:
> 
> [https://wiki.osdev.org/Creating_an_Operating_System](https://wiki.osdev.org/Creating_an_Operating_System)

@Superbro525Alt i am not going to use C Im gonna start by making an epic boot system then use Rust. Assembly + Rust + Bash only languages I will use. Python, Makefile and Bash for my build system.

**Comment by Superbro525Alt** [comment]
Sounds cool
